name: Create Checkpoints Folder
on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Checkpoints Directory
        run: |
          mkdir -p checkpoints
          touch checkpoints/.gitkeep
          
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Action"
          git add checkpoints/.gitkeep
          git commit -m "Add checkpoints folder"
          git push https://shababdd11:${{ secrets.HF_TOKEN }}@huggingface.co/shababdd11/sultan-comfy-env main
